apiVersion: v1
kind: Service
metadata:
  name: unit-converter-service
spec:
  selector:
    app: unit-converter
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
